version: 1.0.0
services:
  - php:
     version: 8.2

ssh-keys:
  DECRYPTABLE_SSH_KEY:
    secure: 2acIshWAndTh1sG0esOn

variables:
  COMPOSER_BIN: $SOURCE_DIR/vendor/bin
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
  SIMPLETEST_DB: "mysql://root:root@localhost/drupal"
  API_KEY: "${decrypt:api_key}"
  API_SECRET: "${decrypt:api_secret}"
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    API_KEY: 
      secure: "skjdhcfoiwejdlwekjfierjfejkfkjefojoe"
    API_SECRET: 
      secure: "sdfjsdlfjsldkfjlsdkjflsdkjfslkdjfslkdjfslkdjf"

events:
  build:
    steps:
      - composer_setup:
          type: script
          script:
            - 'export MD5SUM="`md5sum ~/.ssh/DECRYPTABLE_SSH_KEY`"'
            - 'echo "Verified DECRYPTABLE_SSH_KEY is correctly encrypted."'
            - echo "variables - $COMPOSER_BIN $SIMPLETEST_BASE_URL $API_KEY"
            - echo "Pipelines 2.0.123456"
  post-deploy:
    steps:
      - deploy_to_acquia:
          type: deploy
          script:
            - sleep 2
            - echo "Pipelines 2.0.123456"
  pr-merged:
    steps:
      - deploy_to_acquia:
          type: deploy
          script:
            - sleep 10
            - echo "Pr-Merged event script"
            - echo "Pipelines 2.0.123456"

  pr-closed:
    steps:
      - deploy_to_acquia:
          type: deploy
          script:
            - sleep 5
            - echo "Pr-closed event script"
            - echo "Pipelines 2.0.123456"
