version: 1.1.0
services:
  - php:
      version: 8.2

events:
  build:
    steps:
      - composer:
          type: script
          script:
            # The composer create project files and settings.php db and profile configurations have been provided in the tutorial branch or release. We only need run composer.
            - echo "Hello World !!"
